# Generated by Django 6.0 on 2026-01-14 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único de la plataforma', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la plataforma (Eva, SGA, etc.)', max_length=120)),
                ('codigo', models.CharField(help_text='Código unico de la plataforma', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('eva', 'Eva'), ('sga', 'Sga'), ('cursos', 'Cursos')], help_text='Tipo de plataforma (Eva, Sga, Cursos)', max_length=50)),
                ('url_base', models.URLField(help_text='URL base de la plataforma')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la plataforma', null=True)),
                ('icono_url', models.URLField(blank=True, help_text='URL del icono de la plataforma', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', help_text='Estado actual de la plataforma', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'db_table': 'plataformas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['codigo'], name='plataformas_codigo_adcba6_idx'), models.Index(fields=['tipo'], name='plataformas_tipo_ddebeb_idx'), models.Index(fields=['estado'], name='plataformas_estado_b21d0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegracionSSO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador unico de la integracion SSO', primary_key=True, serialize=False)),
                ('protocolo', models.CharField(choices=[('SAML2', 'SAML 2.0'), ('OAUth2', 'OAuth 2.0'), ('OpenID', 'OpenID Connect')], help_text='Protocolo de autenticacion utilizado', max_length=20)),
                ('client_id', models.CharField(help_text='ID del cliente en Keycloak', max_length=255)),
                ('client_secret', models.CharField(help_text='Secreto del cliente (debe estar encriptado en producción)', max_length=500)),
                ('metadata_url', models.URLField(blank=True, help_text='URL de metadatos SAML/OAuth', max_length=255, null=True)),
                ('callback_url', models.URLField(help_text='URL de callback después del login', max_length=255)),
                ('logout_url', models.URLField(blank=True, help_text='URL de logout de la plataforma', max_length=255, null=True)),
                ('certificado', models.TextField(blank=True, help_text='Certificado SSL público para validación', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si la integración SSO está activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('plataforma', models.OneToOneField(help_text='Plataforma a la que pertenece esta configuracion SSO', on_delete=django.db.models.deletion.CASCADE, to='integration.plataforma')),
            ],
            options={
                'verbose_name': 'Integración SSO',
                'verbose_name_plural': 'Integraciones SSO',
                'db_table': 'integraciones_sso',
                'indexes': [models.Index(fields=['plataforma'], name='integracion_platafo_e0b682_idx'), models.Index(fields=['protocolo'], name='integracion_protoco_2aba56_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sincronizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la sincronización', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('usuarios', 'Usuarios'), ('cursos', 'Cursos'), ('notas', 'Notas'), ('asistencia', 'Asistencia')], help_text='Tipo de datos sincronizados', max_length=50)),
                ('direccion', models.CharField(choices=[('pull', 'Pull (traer datos)'), ('push', 'Push (enviar datos)'), ('bidireccional', 'Bidireccional')], help_text='Dirección de la sincronización', max_length=20)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('parcial', 'Parcial')], help_text='Estado de la sincronización', max_length=20)),
                ('registros_procesados', models.IntegerField(default=0, help_text='Cantidad total de registros procesados')),
                ('registros_exitosos', models.IntegerField(default=0, help_text='Cantidad de registros sincronizados exitosamente')),
                ('registros_fallidos', models.IntegerField(default=0, help_text='Cantidad de registros con error')),
                ('mensaje_error', models.TextField(blank=True, help_text='Detalles del error si la sincronización falló', null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Tiempo que tomó la sincronización en segundos', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la sincronización')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que ejecutó la sincronización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('plataforma', models.ForeignKey(help_text='Plataforma con la que se sincronizó', on_delete=django.db.models.deletion.CASCADE, related_name='sincronizaciones', to='integration.plataforma')),
            ],
            options={
                'verbose_name': 'Sincronización',
                'verbose_name_plural': 'Sincronizaciones',
                'db_table': 'sincronizaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['plataforma'], name='sincronizac_platafo_1a9029_idx'), models.Index(fields=['tipo'], name='sincronizac_tipo_ab87cd_idx'), models.Index(fields=['estado'], name='sincronizac_estado_0d64ba_idx'), models.Index(fields=['creado_en'], name='sincronizac_creado__888ef5_idx')],
            },
        ),
    ]
