# Generated by Django 6.0 on 2026-01-14 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('auth_app', '0001_initial'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accionusuario',
            name='plataforma',
            field=models.ForeignKey(blank=True, help_text='Plataforma donde se realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='integration.plataforma'),
        ),
        migrations.AddField(
            model_name='accionusuario',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión en la que se realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to='auth_app.sesion'),
        ),
        migrations.AddField(
            model_name='accionusuario',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='plataforma',
            field=models.ForeignKey(blank=True, help_text='Plataforma donde se realizó la búsqueda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to='integration.plataforma'),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión en la que se realizó la búsqueda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to='auth_app.sesion'),
        ),
        migrations.AddField(
            model_name='busqueda',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la búsqueda', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='busquedas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionreporte',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó esta configuración', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_reporte', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventonavegacion',
            name='plataforma',
            field=models.ForeignKey(blank=True, help_text='Plataforma donde ocurrió el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_navegacion', to='integration.plataforma'),
        ),
        migrations.AddField(
            model_name='eventonavegacion',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión en la que ocurrió el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_navegacion', to='auth_app.sesion'),
        ),
        migrations.AddField(
            model_name='eventonavegacion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que generó el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_navegacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que exportó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exportaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metricaagregada',
            index=models.Index(fields=['tipo_metrica'], name='metricas_ag_tipo_me_80c67f_idx'),
        ),
        migrations.AddIndex(
            model_name='metricaagregada',
            index=models.Index(fields=['entidad_tipo'], name='metricas_ag_entidad_5ce762_idx'),
        ),
        migrations.AddIndex(
            model_name='metricaagregada',
            index=models.Index(fields=['periodo'], name='metricas_ag_periodo_42c330_idx'),
        ),
        migrations.AddIndex(
            model_name='metricaagregada',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='metricas_ag_fecha_i_fc14d1_idx'),
        ),
        migrations.AddIndex(
            model_name='metricaagregada',
            index=models.Index(fields=['calculado_en'], name='metricas_ag_calcula_621f2b_idx'),
        ),
        migrations.AddField(
            model_name='paginavisitada',
            name='plataforma',
            field=models.ForeignKey(blank=True, help_text='Plataforma donde está la página', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas_visitadas', to='integration.plataforma'),
        ),
        migrations.AddField(
            model_name='paginavisitada',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='Sesión en la que se visitó la página', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas_visitadas', to='auth_app.sesion'),
        ),
        migrations.AddField(
            model_name='paginavisitada',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que visitó la página', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas_visitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='configuracion',
            field=models.ForeignKey(blank=True, help_text='Configuración usada para generar este reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='analytics.configuracionreporte'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='solicitado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que solicitó el reporte', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportacion',
            name='reporte',
            field=models.ForeignKey(help_text='Reporte que fue exportado', on_delete=django.db.models.deletion.CASCADE, related_name='exportaciones', to='analytics.reporte'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['usuario'], name='acciones_us_usuario_357c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['sesion'], name='acciones_us_sesion__22185d_idx'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['plataforma'], name='acciones_us_platafo_ea1081_idx'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['tipo_accion'], name='acciones_us_tipo_ac_4618cf_idx'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['entidad_tipo'], name='acciones_us_entidad_16527f_idx'),
        ),
        migrations.AddIndex(
            model_name='accionusuario',
            index=models.Index(fields=['timestamp'], name='acciones_us_timesta_ed102f_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['usuario'], name='busquedas_usuario_c78479_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['sesion'], name='busquedas_sesion__75d952_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['plataforma'], name='busquedas_platafo_2da412_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['termino_busqueda'], name='busquedas_termino_3f21ae_idx'),
        ),
        migrations.AddIndex(
            model_name='busqueda',
            index=models.Index(fields=['timestamp'], name='busquedas_timesta_5ceab8_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionreporte',
            index=models.Index(fields=['tipo_reporte'], name='configuraci_tipo_re_fda8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionreporte',
            index=models.Index(fields=['frecuencia'], name='configuraci_frecuen_edc0ef_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionreporte',
            index=models.Index(fields=['activo'], name='configuraci_activo_b419a3_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionreporte',
            index=models.Index(fields=['creado_por'], name='configuraci_creado__b5d438_idx'),
        ),
        migrations.AddIndex(
            model_name='eventonavegacion',
            index=models.Index(fields=['usuario'], name='eventos_nav_usuario_1937b3_idx'),
        ),
        migrations.AddIndex(
            model_name='eventonavegacion',
            index=models.Index(fields=['sesion'], name='eventos_nav_sesion__68769d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventonavegacion',
            index=models.Index(fields=['plataforma'], name='eventos_nav_platafo_9b93ae_idx'),
        ),
        migrations.AddIndex(
            model_name='eventonavegacion',
            index=models.Index(fields=['tipo_evento'], name='eventos_nav_tipo_ev_ae4c51_idx'),
        ),
        migrations.AddIndex(
            model_name='eventonavegacion',
            index=models.Index(fields=['timestamp'], name='eventos_nav_timesta_2ced0f_idx'),
        ),
        migrations.AddIndex(
            model_name='paginavisitada',
            index=models.Index(fields=['usuario'], name='paginas_vis_usuario_607561_idx'),
        ),
        migrations.AddIndex(
            model_name='paginavisitada',
            index=models.Index(fields=['sesion'], name='paginas_vis_sesion__0db0bc_idx'),
        ),
        migrations.AddIndex(
            model_name='paginavisitada',
            index=models.Index(fields=['plataforma'], name='paginas_vis_platafo_6a30ff_idx'),
        ),
        migrations.AddIndex(
            model_name='paginavisitada',
            index=models.Index(fields=['timestamp'], name='paginas_vis_timesta_8b302e_idx'),
        ),
        migrations.AddIndex(
            model_name='paginavisitada',
            index=models.Index(fields=['rebote'], name='paginas_vis_rebote_72ce6d_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['configuracion'], name='reportes_configu_308a08_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado'], name='reportes_estado_7afa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['solicitado_por'], name='reportes_solicit_fcfcba_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['periodo_inicio', 'periodo_fin'], name='reportes_periodo_6941d0_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['generado_en'], name='reportes_generad_d1f6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['reporte'], name='exportacion_reporte_175c80_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['usuario'], name='exportacion_usuario_19e9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['formato'], name='exportacion_formato_be00a5_idx'),
        ),
        migrations.AddIndex(
            model_name='exportacion',
            index=models.Index(fields=['exportado_en'], name='exportacion_exporta_1164dc_idx'),
        ),
    ]
