# Generated by Django 6.0 on 2026-02-10 15:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
        ("system_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeDashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del mensaje",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título corto del mensaje", max_length=255
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(help_text="Contenido completo del mensaje"),
                ),
                (
                    "imagen_url",
                    models.URLField(
                        blank=True,
                        help_text="URL de la imagen opcional para el mensaje",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "color_fondo",
                    models.CharField(
                        blank=True,
                        default="#e3f2fd",
                        help_text="Color de fondo en formato hexadecimal (ej: #e3f2fd)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "enlace_url",
                    models.URLField(
                        blank=True,
                        help_text="URL del enlace opcional",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "enlace_texto",
                    models.CharField(
                        blank=True,
                        help_text="Texto del botón/enlace (ej: 'Ver más', 'Ir al calendario')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Si el mensaje está activo y visible"
                    ),
                ),
                (
                    "prioridad",
                    models.IntegerField(
                        default=100,
                        help_text="Orden de visualización (1 = más prioritario)",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        blank=True,
                        help_text="Desde cuándo se muestra el mensaje (NULL = desde siempre)",
                        null=True,
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Hasta cuándo se muestra el mensaje (NULL = sin límite)",
                        null=True,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha y hora de última actualización"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que creó el mensaje",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mensajes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de Dashboard",
                "verbose_name_plural": "Mensajes de Dashboard",
                "db_table": "mensajes_dashboard",
                "ordering": ["prioridad", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="MensajeDashboardRol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la relación",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "asignado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha y hora de asignación"
                    ),
                ),
                (
                    "mensaje",
                    models.ForeignKey(
                        help_text="Mensaje asignado",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="system_app.mensajedashboard",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        help_text="Rol destinatario del mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes_dashboard",
                        to="auth_app.rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Mensaje-Rol",
                "verbose_name_plural": "Asignaciones Mensaje-Rol",
                "db_table": "mensajes_dashboard_roles",
            },
        ),
        migrations.AddIndex(
            model_name="mensajedashboard",
            index=models.Index(fields=["activo"], name="mensajes_da_activo_c91bec_idx"),
        ),
        migrations.AddIndex(
            model_name="mensajedashboard",
            index=models.Index(
                fields=["fecha_inicio"], name="mensajes_da_fecha_i_a3e116_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajedashboard",
            index=models.Index(
                fields=["fecha_fin"], name="mensajes_da_fecha_f_10854e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajedashboard",
            index=models.Index(
                fields=["prioridad"], name="mensajes_da_priorid_a211c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajedashboard",
            index=models.Index(
                fields=["creado_por"], name="mensajes_da_creado__88bc14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajedashboardrol",
            index=models.Index(
                fields=["mensaje"], name="mensajes_da_mensaje_103f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mensajedashboardrol",
            index=models.Index(fields=["rol"], name="mensajes_da_rol_id_94df87_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mensajedashboardrol",
            unique_together={("mensaje", "rol")},
        ),
    ]
