# Generated by Django 6.0 on 2026-02-11 15:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system_app", "0002_mensajedashboard_mensajedashboardrol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivoSistema",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del archivo",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre descriptivo del archivo", max_length=255
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Archivo subido al sistema",
                        upload_to="sistema/archivos/%Y/%m/",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        help_text="Estado del archivo",
                        max_length=20,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo del Sistema",
                "verbose_name_plural": "Archivos del Sistema",
                "db_table": "archivos_sistema",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado"], name="archivos_si_estado_491ffb_idx"
                    ),
                    models.Index(
                        fields=["creado_en"], name="archivos_si_creado__2e0e3b_idx"
                    ),
                ],
            },
        ),
    ]
