# Generated by Django 6.0 on 2026-01-14 15:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del usuario', primary_key=True, serialize=False)),
                ('nombres', models.CharField(help_text='Nombres del usuario', max_length=100)),
                ('apellidos', models.CharField(help_text='Apellidos del usuario', max_length=100)),
                ('cedula', models.CharField(help_text='Cédula del usuario', max_length=10, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono del usuario', max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del usuario', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado')], default='activo', help_text='Estado del usuario', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del usuario')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización del usuario')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación del usuario (soft delete)', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-creado_en'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del permiso', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del permiso', max_length=100, unique=True)),
                ('codigo', models.CharField(help_text='Código del permiso (ej: portal.read, usuarios.create)', max_length=50, unique=True)),
                ('modulo', models.CharField(choices=[('portal', 'Portal'), ('usuarios', 'Usuarios'), ('analytics', 'Analytics'), ('plataformas', 'Plataformas'), ('sistema', 'Sistema')], help_text='Módulo al que pertenece el permiso', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del permiso', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el permiso está activo o no')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del permiso')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'permisos',
                'ordering': ['modulo', 'codigo'],
                'indexes': [models.Index(fields=['modulo'], name='permisos_modulo_b603c7_idx'), models.Index(fields=['codigo'], name='permisos_codigo_111d3c_idx'), models.Index(fields=['nombre'], name='permisos_nombre_61d4e5_idx')],
            },
        ),
        migrations.CreateModel(
            name='PreferenciasUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de las preferencias', primary_key=True, serialize=False)),
                ('idioma', models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', help_text='Idioma de la interfaz', max_length=5)),
                ('tema', models.CharField(choices=[('claro', 'Claro'), ('oscuro', 'Oscuro'), ('auto', 'Automático')], default='claro', help_text='Tema visual de la interfaz', max_length=20)),
                ('zona_horaria', models.CharField(default='America/Guayaquil', help_text='Zona horaria del usuario', max_length=50)),
                ('notificaciones_email', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico')),
                ('dashboard_layout', models.JSONField(default=dict, help_text='Configuración del layout del dashboard en formato JSON')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización')),
                ('usuario', models.OneToOneField(help_text='Usuario dueño de estas preferencias', on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de Usuario',
                'verbose_name_plural': 'Preferencias de Usuarios',
                'db_table': 'preferencias_usuario',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único del rol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del rol (Super Admin, profesor, estudiante, etc.)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del rol', null=True)),
                ('nivel', models.IntegerField(help_text='Nivel jerárquico del rol (1=más alto, 6=más bajo)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el rol está activo o no')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del rol')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha y hora de actualización del rol')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['nivel'],
                'indexes': [models.Index(fields=['nombre'], name='roles_nombre_ec8c3b_idx'), models.Index(fields=['nivel'], name='roles_nivel_6cb014_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del rol-permiso', primary_key=True, serialize=False)),
                ('asignado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la asignación del permiso')),
                ('permiso', models.ForeignKey(help_text='Permiso que se asigna al rol', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='auth_app.permiso')),
                ('rol', models.ForeignKey(help_text='Rol al que se le asigna el permiso', on_delete=django.db.models.deletion.CASCADE, related_name='rol_permisos', to='auth_app.rol')),
            ],
            options={
                'verbose_name': 'Rol-Permiso',
                'verbose_name_plural': 'Roles-Permisos',
                'db_table': 'rol_permisos',
                'ordering': ['rol', 'permiso'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la sesión', primary_key=True, serialize=False)),
                ('token_sesion', models.CharField(help_text='Token JWT de la sesión', max_length=500, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP desde donde se conectó')),
                ('user_agent', models.TextField(help_text='Información del navegador y sistema operativo')),
                ('dispositivo', models.CharField(choices=[('desktop', 'Escritorio'), ('mobile', 'Móvil'), ('tablet', 'Tablet')], help_text='Tipo de dispositivo usado', max_length=50)),
                ('inicio_sesion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de inicio de sesión')),
                ('ultimo_acceso', models.DateTimeField(auto_now=True, help_text='Última actividad registrada')),
                ('cierre_sesion', models.DateTimeField(blank=True, help_text='Fecha y hora de cierre (NULL si está activa)', null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Duración total de la sesión en segundos', null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario dueño de esta sesión', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión',
                'verbose_name_plural': 'Sesiones',
                'db_table': 'sesiones',
                'ordering': ['-inicio_sesion'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la asignación', primary_key=True, serialize=False)),
                ('asignado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la asignación del rol')),
                ('asignado_por', models.ForeignKey(blank=True, help_text='Usuario administrador que asignó el rol', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(help_text='Rol que se asigna al usuario', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to='auth_app.rol')),
                ('usuario', models.ForeignKey(help_text='Usuario al que se le asigna el rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario-Rol',
                'verbose_name_plural': 'Usuarios-Roles',
                'db_table': 'usuarios_roles',
                'ordering': ['-asignado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['username'], name='usuarios_usernam_7abab6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='usuarios_cedula_dd8531_idx'),
        ),
        migrations.AddIndex(
            model_name='preferenciasusuario',
            index=models.Index(fields=['usuario'], name='preferencia_usuario_485768_idx'),
        ),
        migrations.AddIndex(
            model_name='rolpermiso',
            index=models.Index(fields=['rol'], name='rol_permiso_rol_id_582f08_idx'),
        ),
        migrations.AddIndex(
            model_name='rolpermiso',
            index=models.Index(fields=['permiso'], name='rol_permiso_permiso_c75d67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolpermiso',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['usuario'], name='sesiones_usuario_710990_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['inicio_sesion'], name='sesiones_inicio__e5499b_idx'),
        ),
        migrations.AddIndex(
            model_name='sesion',
            index=models.Index(fields=['ip_address'], name='sesiones_ip_addr_323ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['usuario'], name='usuarios_ro_usuario_5cf550_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['rol'], name='usuarios_ro_rol_id_b76bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariorol',
            index=models.Index(fields=['asignado_en'], name='usuarios_ro_asignad_1aa0c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariorol',
            unique_together={('usuario', 'rol')},
        ),
    ]
