# Generated by Django 6.0 on 2026-01-14 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la configuración', primary_key=True, serialize=False)),
                ('clave', models.CharField(help_text='Nombre de la configuración (ej: nombre_institucion, modo_mantenimiento)', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('number', 'Número'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', help_text='Tipo de dato del valor', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de qué hace esta configuración', null=True)),
                ('categoria', models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('seguridad', 'Seguridad'), ('integracion', 'Integración'), ('analytics', 'Analytics')], default='general', help_text='Categoría de la configuración', max_length=50)),
                ('editable', models.BooleanField(default=True, help_text='Si la configuración puede cambiarse desde la interfaz')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
                'ordering': ['categoria', 'clave'],
                'indexes': [models.Index(fields=['clave'], name='configuraci_clave_2555cf_idx'), models.Index(fields=['categoria'], name='configuraci_categor_1e5d8e_idx'), models.Index(fields=['editable'], name='configuraci_editabl_f47c47_idx')],
            },
        ),
        migrations.CreateModel(
            name='TareaProgramada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la tarea', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la tarea', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de qué hace la tarea', null=True)),
                ('tipo', models.CharField(choices=[('maintenance', 'Mantenimiento'), ('backup', 'Backup'), ('analytics', 'Analytics'), ('sync', 'Sincronización'), ('cleanup', 'Limpieza')], help_text='Tipo de tarea', max_length=50)),
                ('comando', models.TextField(help_text='Comando o script a ejecutar')),
                ('frecuencia', models.CharField(help_text='Expresión cron (ej: */5 * * * * = cada 5 minutos)', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='Si la tarea está activa')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, help_text='Fecha y hora de última ejecución', null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, help_text='Fecha y hora de próxima ejecución', null=True)),
                ('estado_ultima', models.CharField(blank=True, choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('ejecutando', 'Ejecutando')], help_text='Estado de la última ejecución', max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la tarea')),
            ],
            options={
                'verbose_name': 'Tarea Programada',
                'verbose_name_plural': 'Tareas Programadas',
                'db_table': 'tareas_programadas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['tipo'], name='tareas_prog_tipo_867856_idx'), models.Index(fields=['activa'], name='tareas_prog_activa_4922d4_idx'), models.Index(fields=['proxima_ejecucion'], name='tareas_prog_proxima_eddf53_idx'), models.Index(fields=['estado_ultima'], name='tareas_prog_estado__4cfa0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del log', primary_key=True, serialize=False)),
                ('accion', models.CharField(help_text='Acción realizada (CREAR_USUARIO, MODIFICAR_CURSO, etc)', max_length=100)),
                ('entidad_tipo', models.CharField(help_text='Tipo de entidad afectada (usuario, curso, etc)', max_length=50)),
                ('entidad_id', models.CharField(help_text='ID de la entidad afectada', max_length=255)),
                ('valores_anteriores', models.JSONField(blank=True, default=dict, help_text='Estado de la entidad ANTES del cambio')),
                ('valores_nuevos', models.JSONField(blank=True, default=dict, help_text='Estado de la emtodad despues del cambio')),
                ('ip_address', models.GenericIPAddressField(help_text='Dirección IP desde donde se realizó la acción')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador usado', null=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', help_text='Nivel de importancia del log', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la acción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'logs_auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario'], name='logs_audito_usuario_423ef8_idx'), models.Index(fields=['accion'], name='logs_audito_accion_ba8456_idx'), models.Index(fields=['entidad_tipo'], name='logs_audito_entidad_6fe8b7_idx'), models.Index(fields=['nivel'], name='logs_audito_nivel_c44695_idx'), models.Index(fields=['timestamp'], name='logs_audito_timesta_46db59_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la notificación', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('sistema', 'Sistema'), ('academico', 'Académico'), ('seguridad', 'Seguridad'), ('alerta', 'Alerta')], help_text='Tipo de notificación', max_length=50)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=255)),
                ('mensaje', models.TextField(help_text='Contenido de la notificación')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', help_text='Nivel de prioridad', max_length=20)),
                ('leida', models.BooleanField(default=False, help_text='Si la notificación fue leída')),
                ('leida_en', models.DateTimeField(blank=True, help_text='Fecha y hora en que fue leída', null=True)),
                ('url_accion', models.URLField(blank=True, help_text='URL si la notificación requiere una acción', max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la notificación')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario destinatario de la notificación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario'], name='notificacio_usuario_17ba4e_idx'), models.Index(fields=['tipo'], name='notificacio_tipo_f5d897_idx'), models.Index(fields=['prioridad'], name='notificacio_priorid_eb1da5_idx'), models.Index(fields=['leida'], name='notificacio_leida_8f2b73_idx'), models.Index(fields=['creado_en'], name='notificacio_creado__94437b_idx')],
            },
        ),
    ]
