# Generated by Django 6.0 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_app', '0003_archivosistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='valores_nuevos',
            field=models.JSONField(blank=True, default=dict, help_text='Estado de la entidad despues del cambio'),
        ),
    ]
