# Generated by Django 6.0 on 2026-01-14 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la acción del usuario', primary_key=True, serialize=False)),
                ('tipo_accion', models.CharField(help_text='Tipo de acción: inscripcion_curso, descarga_recurso, envio_formulario, etc', max_length=100)),
                ('entidad_tipo', models.CharField(help_text='Tipo de entidad afectada: curso, recurso, certificado, formulario', max_length=50)),
                ('entidad_id', models.CharField(help_text='ID de la entidad afectada en la plataforma externa', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la acción en formato JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción')),
            ],
            options={
                'verbose_name': 'Acción de Usuario',
                'verbose_name_plural': 'Acciones de Usuario',
                'db_table': 'acciones_usuario',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Busqueda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la búsqueda', primary_key=True, serialize=False)),
                ('termino_busqueda', models.CharField(help_text='Texto que buscó el usuario', max_length=255)),
                ('cantidad_resultados', models.IntegerField(default=0, help_text='Número de resultados encontrados')),
                ('resultado_clickeado', models.URLField(blank=True, help_text='URL del resultado que clickeó el usuario', max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la búsqueda')),
            ],
            options={
                'verbose_name': 'Búsqueda',
                'verbose_name_plural': 'Búsquedas',
                'db_table': 'busquedas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la configuración', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del reporte', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del reporte', null=True)),
                ('tipo_reporte', models.CharField(choices=[('cursos', 'Cursos'), ('usuarios', 'Usuarios'), ('analytics', 'Analytics'), ('plataformas', 'Plataformas'), ('general', 'General')], help_text='Tipo/categoría del reporte', max_length=50)),
                ('filtros', models.JSONField(blank=True, default=dict, help_text='Filtros configurados en formato JSON')),
                ('columnas', models.JSONField(blank=True, default=list, help_text='Columnas a mostrar en el reporte')),
                ('visualizaciones', models.JSONField(blank=True, default=list, help_text='Gráficos y visualizaciones configurados')),
                ('frecuencia', models.CharField(choices=[('manual', 'Manual'), ('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='manual', help_text='Frecuencia de generación automática', max_length=20)),
                ('destinatarios_email', models.JSONField(blank=True, default=list, help_text='Lista de emails que reciben el reporte automático')),
                ('activo', models.BooleanField(default=True, help_text='Si la configuración está activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'db_table': 'configuraciones_reporte',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoNavegacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del evento', primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(help_text='Tipo de evento: click, scroll, pageview, etc', max_length=50)),
                ('url', models.URLField(help_text='URL donde ocurrió el evento', max_length=500)),
                ('elemento_html', models.CharField(blank=True, help_text='Elemento HTML clickeado (ej: button#submit)', max_length=255, null=True)),
                ('coordenadas', models.JSONField(blank=True, default=dict, help_text='Posición X,Y del evento en formato JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta del evento')),
            ],
            options={
                'verbose_name': 'Evento de Navegación',
                'verbose_name_plural': 'Eventos de Navegación',
                'db_table': 'eventos_navegacion',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Exportacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la exportación', primary_key=True, serialize=False)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel (XLSX)'), ('csv', 'CSV')], help_text='Formato de exportación', max_length=10)),
                ('ruta_descarga', models.CharField(help_text='Ubicación del archivo exportado', max_length=500)),
                ('tamano_bytes', models.BigIntegerField(help_text='Tamaño del archivo exportado en bytes')),
                ('exportado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la exportación')),
            ],
            options={
                'verbose_name': 'Exportación',
                'verbose_name_plural': 'Exportaciones',
                'db_table': 'exportaciones',
                'ordering': ['-exportado_en'],
            },
        ),
        migrations.CreateModel(
            name='MetricaAgregada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la métrica', primary_key=True, serialize=False)),
                ('tipo_metrica', models.CharField(help_text='Tipo de métrica: total_visitas, promedio_tiempo, ranking_cursos, etc', max_length=100)),
                ('entidad_tipo', models.CharField(help_text='Tipo de entidad: curso, plataforma, usuario, general', max_length=50)),
                ('entidad_id', models.CharField(blank=True, help_text='ID de la entidad específica (NULL si es métrica general)', max_length=255, null=True)),
                ('periodo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('anual', 'Anual')], help_text='Período de agregación', max_length=20)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor calculado de la métrica', max_digits=15)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales de la métrica en formato JSON')),
                ('calculado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se calculó la métrica')),
            ],
            options={
                'verbose_name': 'Métrica Agregada',
                'verbose_name_plural': 'Métricas Agregadas',
                'db_table': 'metricas_agregadas',
                'ordering': ['-calculado_en'],
            },
        ),
        migrations.CreateModel(
            name='PaginaVisitada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la página visitada', primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='URL de la página visitada', max_length=500)),
                ('titulo_pagina', models.CharField(blank=True, help_text='Título de la página (HTML <title>)', max_length=255, null=True)),
                ('referrer', models.URLField(blank=True, help_text='URL de donde vino el usuario (página anterior)', max_length=500, null=True)),
                ('tiempo_permanencia', models.IntegerField(default=0, help_text='Tiempo en segundos que permaneció en la página')),
                ('rebote', models.BooleanField(default=False, help_text='True si el usuario salió sin interactuar (bounce)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la visita')),
            ],
            options={
                'verbose_name': 'Página Visitada',
                'verbose_name_plural': 'Páginas Visitadas',
                'db_table': 'paginas_visitadas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del reporte', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del reporte generado', max_length=255)),
                ('periodo_inicio', models.DateField(help_text='Fecha de inicio de los datos del reporte')),
                ('periodo_fin', models.DateField(help_text='Fecha de fin de los datos del reporte')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', help_text='Estado actual del reporte', max_length=20)),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta donde se guardó el archivo del reporte', max_length=500, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la generación falló', null=True)),
                ('generado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de generación')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
                'ordering': ['-generado_en'],
            },
        ),
    ]
