# Generated by Django 6.0 on 2026-01-26 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_noticiaspopup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del interesado",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        help_text="Nombres del interesado", max_length=100
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        help_text="Apellidos del interesado", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico de contacto", max_length=254
                    ),
                ),
                (
                    "telefono",
                    models.CharField(help_text="Número de teléfono", max_length=15),
                ),
                (
                    "mensaje",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje o consulta adicional del interesado",
                        null=True,
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora del registro de interés",
                    ),
                ),
                (
                    "atendido",
                    models.BooleanField(
                        default=False, help_text="Si ya fue contactado por el instituto"
                    ),
                ),
                (
                    "fecha_atencion",
                    models.DateTimeField(
                        blank=True, help_text="Fecha en que fue atendido", null=True
                    ),
                ),
                (
                    "notas_seguimiento",
                    models.TextField(
                        blank=True,
                        help_text="Notas del equipo sobre el seguimiento",
                        null=True,
                    ),
                ),
                (
                    "curso_interes",
                    models.ForeignKey(
                        help_text="Programa/Curso de interés",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interesados",
                        to="content.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Interesado",
                "verbose_name_plural": "Interesados",
                "db_table": "interesados",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["curso_interes"], name="interesados_curso_i_a13d01_idx"
                    ),
                    models.Index(fields=["email"], name="interesados_email_378d5e_idx"),
                    models.Index(
                        fields=["atendido"], name="interesados_atendid_192e4a_idx"
                    ),
                    models.Index(
                        fields=["fecha_registro"], name="interesados_fecha_r_9a27ab_idx"
                    ),
                ],
            },
        ),
    ]
