# Generated by Django 6.0 on 2026-01-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_categoriacurso_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentotransparencia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("presupuesto", "Presupuesto"),
                    ("reglamentos", "Reglamentos"),
                    ("actas", "Actas"),
                    ("informes", "Informes"),
                    ("convenios", "Convenios"),
                    ("resoluciones", "Resoluciones"),
                    ("normativa", "Normativa"),
                    ("financiero", "Financiero"),
                ],
                help_text="Categoría del documento",
                max_length=100,
            ),
        ),
    ]
