# Generated by Django 6.0 on 2026-02-11 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0006_alter_documentotransparencia_categoria"),
        ("integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinador o autoridad responsable del curso",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos_coordinados",
                to="content.autoridad",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="costo_matricula",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo de matrícula en USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="costo_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Costo total del curso en USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="cuotas",
            field=models.IntegerField(
                blank=True,
                help_text="Número de cuotas disponibles para pago",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="fecha_fin_publicidad",
            field=models.DateField(
                blank=True,
                help_text="Fecha hasta cuando se muestra el curso en web",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="fecha_inicio_publicidad",
            field=models.DateField(
                blank=True,
                help_text="Fecha desde cuando se publica el curso en web",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("matutina", "Matutina"),
                    ("vespertina", "Vespertina"),
                    ("nocturna", "Nocturna"),
                    ("intensiva", "Intensiva"),
                    ("mixta", "Mixta"),
                ],
                help_text="Jornada en la que se imparte el curso",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="malla_curricular",
            field=models.ImageField(
                blank=True,
                help_text="Imagen de la malla curricular",
                null=True,
                upload_to="cursos/mallas_curriculares/",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="modalidad",
            field=models.CharField(
                blank=True,
                choices=[
                    ("presencial", "Presencial"),
                    ("virtual", "Virtual"),
                    ("hibrida", "Híbrida"),
                    ("dual", "Dual"),
                ],
                help_text="Modalidad del curso",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="perfil_profesional",
            field=models.TextField(
                blank=True, help_text="Perfil profesional del egresado", null=True
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="presentacion",
            field=models.TextField(
                blank=True, help_text="Presentación/introducción del curso", null=True
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="resolucion",
            field=models.TextField(
                blank=True,
                help_text="Número de resolución oficial del curso",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="titulo_obtenido",
            field=models.CharField(
                blank=True,
                help_text="Título que obtiene el estudiante (ej: Tecnólogo en...)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(
                fields=["coordinador"], name="cursos_coordin_3e2304_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(fields=["jornada"], name="cursos_jornada_8ed3c0_idx"),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(fields=["modalidad"], name="cursos_modalid_659e74_idx"),
        ),
    ]
