# Generated by Django 6.0 on 2026-02-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_curso_coordinador_curso_costo_matricula_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="curso",
            name="cursos_profeso_e217b3_idx",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="profesor_responsable",
        ),
    ]
