# Generated by Django 6.0 on 2026-02-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0010_remove_post_etiquetas_etiqueta_post_etiquetas"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoridad",
            name="titulo_autoridad",
            field=models.CharField(
                blank=True,
                help_text="Título académico o profesional (ej: PhD., Msc., Ing., Dr.)",
                max_length=100,
                null=True,
            ),
        ),
    ]
