# Generated by Django 6.0 on 2026-02-12 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0011_autoridad_titulo_autoridad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentotransparencia",
            name="subcategoria",
            field=models.CharField(
                choices=[
                    ("presupuesto", "Presupuesto"),
                    ("reglamentos", "Reglamentos"),
                    ("actas", "Actas"),
                    ("informes", "Informes"),
                    ("convenios", "Convenios"),
                    ("resoluciones", "Resoluciones"),
                    ("normativa", "Normativa"),
                    ("financiero", "Financiero"),
                ],
                default="presupuesto",
                help_text="Subcategoría del documento",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="documentotransparencia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("normativa institucional", "Normativa Institucional"),
                    ("información económica", "Infromación Económica"),
                    ("rendición de cuentas", "Rendición de Cuentas"),
                    ("planificación institucional", "Planificación Institucional"),
                ],
                help_text="Categoría principal del documento",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="documentotransparencia",
            index=models.Index(
                fields=["subcategoria"], name="documentos__subcate_1cb7cb_idx"
            ),
        ),
    ]
