# Generated by Django 6.0.2 on 2026-02-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_documentotransparencia_subcategoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='duracion_horas',
            new_name='duracion_valor',
        ),
        # 2. NO pongas AddField de duracion_valor aquí, porque ya existe.
        
        # 3. Agregamos los campos que son realmente nuevos
        migrations.AddField(
            model_name='curso',
            name='clases',
            field=models.IntegerField(blank=True, help_text='Número de clases', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, help_text='Rango de horas', max_length=100, null=True),
        ),
        
        migrations.AddField(
            model_name='curso',
            name='unidad_duracion',
            field=models.CharField(choices=[('horas', 'Horas'), ('anios', 'Años')], default='horas', help_text='Define si la duración es en horas o años', max_length=10),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(choices=[('rector', 'Rector'), ('vicerrector', 'Vicerrector'), ('coordinador_academico', 'Coordinador Académico'), ('secretario_general', 'Secretario General'), ('director_carrera', 'Director de Carrera'), ('coordinador_investigacion', 'Coordinador de Investigación'), ('representante_docente', 'Representante Docentes')], help_text='Cargo que desempeña', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de matrícula inicial en USD', max_digits=10, null=True, verbose_name='Costo de Matrícula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo total del curso o costo por cada ciclo/semestre', max_digits=10, null=True, verbose_name='Costo por Ciclo / Total'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cuotas',
            field=models.IntegerField(blank=True, help_text='Cantidad de cuotas en las que se puede diferir el pago', null=True, verbose_name='Número de Cuotas'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo_obtenido',
            field=models.CharField(blank=True, help_text='Título que obtiene el estudiante', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='subcategoria',
            field=models.CharField(choices=[('presupuesto', 'Presupuesto'), ('reglamentos', 'Reglamentos'), ('actas', 'Actas'), ('informes', 'Informes'), ('convenios', 'Convenios'), ('resoluciones', 'Resoluciones'), ('normativa', 'Normativa'), ('financiero', 'Financiero'), ('estatutos', 'Estatutos'), ('politicas', 'Políticas'), ('protocolos', 'Protocolos'), ('manuales', 'Manuales'), ('guias', 'Guías'), ('remuneraciones', 'Remuneraciones'), ('estados_financieros', 'Estados Financieros'), ('planificacion_operativa', 'Planificación Operativa'), ('planificacion_estrategica', 'Planificación Estratégica')], help_text='Subcategoría del documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'Noticia'), ('blog', 'Blog'), ('publicacion', 'Publicación Científica'), ('hitos_logros', 'Hitos y Logros')], help_text='Tipo de contenido', max_length=50),
        ),
    ]
