# Generated by Django 6.0 on 2026-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_curso_duracion_horas_curso_clases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(choices=[('rector', 'Rector'), ('vicerrector', 'Vicerrector'), ('coordinador_academico', 'Coordinador Académico'), ('secretario_general', 'Secretario General'), ('director_carrera', 'Director de Carrera'), ('coordinador_investigacion', 'Coordinador de Investigación'), ('representante_docente', 'Representante Docentes'), ('representante_estudiante', 'Representante Estudiantes'), ('consejo_regentes', 'Consejo de Regentes')], help_text='Cargo que desempeña', max_length=100),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='clases',
            field=models.CharField(blank=True, help_text='Días de clases', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_valor',
            field=models.IntegerField(blank=True, help_text='Cantidad numérica de la duración', null=True),
        ),
    ]
