# Generated by Django 6.0 on 2026-04-20 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_autoridad_cargo_alter_autoridad_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF asociado al post (opcional, útil para Revistas o Blogs)', null=True, upload_to='posts_pdfs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='post',
            name='autor_texto',
            field=models.CharField(blank=True, help_text='Nombre libre del autor (usado cuando el autor no es un usuario del sistema)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('academico', 'Académico'), ('eventos', 'Eventos'), ('deportes', 'Deportes'), ('comunicados', 'Comunicados')], help_text='Clasificación de la noticia', max_length=50, null=True),
        ),
    ]
