# Generated by Django 6.0 on 2026-04-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_post_archivo_pdf_post_autor_texto_post_clasificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Indica si el curso debe aparecer en la sección de destacados'),
        ),
    ]
