# Generated by Django 6.0 on 2026-04-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_curso_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('carrera', 'Carrera (Tercer Nivel)'), ('moodle', 'Curso Moodle Destacado')], default='carrera', help_text='Define si es una Carrera de la institución o un curso destacado de Moodle', max_length=20),
        ),
    ]
