# Generated by Django 6.0 on 2026-04-28 15:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_curso_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.curso',),
        ),
        migrations.CreateModel(
            name='CursoMoodle',
            fields=[
            ],
            options={
                'verbose_name': 'Curso Moodle Destacado',
                'verbose_name_plural': 'Cursos Moodle Destacados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.curso',),
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Programa Académico (Base)', 'verbose_name_plural': 'Programas Académicos (Base)'},
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seccion', models.CharField(choices=[('mesa_tecnica', 'Mesa Técnica'), ('ruta_aprendizaje', 'Ruta de Aprendizaje'), ('historia', 'Nuestra Historia'), ('inicio', 'Inicio Principal')], help_text='Sección donde aparecerá esta imagen en el frontend', max_length=50)),
                ('titulo', models.CharField(blank=True, help_text='Título o nombre descriptivo de la imagen (Opcional)', max_length=150, null=True)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen (Ej. Imgur, Cloudinary)', max_length=500, null=True)),
                ('imagen_archivo', models.ImageField(blank=True, help_text='O sube el archivo directamente', null=True, upload_to='carruseles/')),
                ('url_destino', models.URLField(blank=True, help_text='URL a la que redirigirá al hacer clic (Especial para Mesa Técnica)', max_length=500, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden en el que aparecerá en el carrusel (0 es el primero)')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la imagen está visible')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'db_table': 'imagenes_carrusel',
                'ordering': ['seccion', 'orden', '-creado_en'],
                'indexes': [models.Index(fields=['seccion', 'activo'], name='imagenes_ca_seccion_a7bc7f_idx')],
            },
        ),
    ]
