# Generated by Django 6.0 on 2026-04-28 16:56



import django.db.models.deletion

import uuid

from django.conf import settings

from django.db import migrations, models





class Migration(migrations.Migration):



    dependencies = [

        ('auth_app', '0001_initial'),

        ('content', '0018_carrera_cursomoodle_alter_curso_options_and_more'),

        ('integration', '0001_initial'),

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),

    ]



    operations = [

        migrations.CreateModel(

            name='BotonSoporte',

            fields=[

                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del botón', primary_key=True, serialize=False)),

                ('nombre', models.CharField(help_text='Nombre del botón (ej: Soporte Moodle, Soporte General)', max_length=100)),

                ('enlace_url', models.URLField(help_text='URL de destino del botón (ej: enlace de WhatsApp)', max_length=500)),

                ('plataforma', models.CharField(blank=True, help_text='A qué plataforma pertenece (ej: moodle, sgac)', max_length=50, null=True)),

                ('icono', models.CharField(blank=True, help_text='Clase de icono o nombre de icono (opcional)', max_length=100, null=True)),

                ('activo', models.BooleanField(default=True, help_text='Si el botón está visible en el frontend')),

                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),

                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),

                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),

            ],

            options={

                'verbose_name': 'Botón de Soporte',

                'verbose_name_plural': 'Botones de Soporte',

                'db_table': 'botones_soporte',

                'ordering': ['orden', 'nombre'],

            },

        ),

        migrations.AlterModelOptions(

            name='categoriacurso',

            options={'verbose_name': 'Categoría de Curso', 'verbose_name_plural': 'Categorías de Cursos'},

        ),

        migrations.AlterModelOptions(

            name='curso',

            options={'ordering': ['-creado_en'], 'verbose_name': 'Programa Académico (Base)', 'verbose_name_plural': 'Programas Académicos (Base)'},

        ),

        migrations.AlterModelOptions(

            name='imagencarrusel',

            options={'ordering': ['seccion', 'orden', '-creado_en'], 'verbose_name': 'Imagen de Carrusel', 'verbose_name_plural': 'Imágenes de Carrusel'},

        ),

        migrations.AlterModelOptions(

            name='recursoacademico',

            options={'ordering': ['curso', 'orden'], 'verbose_name': 'Recurso Académico', 'verbose_name_plural': 'Recursos Académicos'},

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del acceso', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='plataforma',

            field=models.ForeignKey(blank=True, help_text='Plataforma donde se accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='integration.plataforma'),

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='sesion',

            field=models.ForeignKey(blank=True, help_text='Sesión en la que se accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='auth_app.sesion'),

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='tiempo_acceso_segundos',

            field=models.IntegerField(default=0, help_text='Tiempo que el usuario pasó con el recurso (en segundos)'),

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='tipo_acceso',

            field=models.CharField(choices=[('descarga', 'Descarga'), ('visualizacion', 'Visualización'), ('reproduccion', 'Reproducción')], help_text='Tipo de acceso realizado', max_length=50),

        ),

        migrations.AlterField(

            model_name='accesorecurso',

            name='usuario',

            field=models.ForeignKey(blank=True, help_text='Usuario que accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to=settings.AUTH_USER_MODEL),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='activo',

            field=models.BooleanField(default=True, help_text='Si la autoridad está actualmente en el cargo'),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='biografia',

            field=models.TextField(blank=True, help_text='Biografía profesional y trayectoria', null=True),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='cargo',

            field=models.CharField(choices=[('rector', 'Rector'), ('vicerrector', 'Vicerrector'), ('coordinador_academico', 'Coordinador Académico'), ('secretario_general', 'Secretario General'), ('director_carrera', 'Director de Carrera'), ('coordinador_investigacion', 'Coordinador de Investigación'), ('representante_docente', 'Representante Docentes'), ('representante_estudiante', 'Representante Estudiantes'), ('consejo_regentes', 'Consejo de Regentes')], help_text='Cargo que desempeña', max_length=100),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='fecha_fin',

            field=models.DateField(blank=True, help_text='Fecha de fin del cargo (NULL si está activo)', null=True),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='fotografia',

            field=models.ImageField(blank=True, help_text='Fotografía oficial de la autoridad', null=True, upload_to='autoridades/'),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la autoridad', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='orden',

            field=models.IntegerField(default=0, help_text='Orden de visualización en la web (menor = primero)'),

        ),

        migrations.AlterField(

            model_name='autoridad',

            name='titulo_autoridad',

            field=models.CharField(blank=True, help_text='Título académico o profesional (ej: PhD., Msc., Ing., Dr.)', max_length=100, null=True),

        ),

        migrations.AlterField(

            model_name='categoriacurso',

            name='coordinacion',

            field=models.IntegerField(choices=[(1, 'Vicerrectorado'), (2, 'Educación Continua')], help_text='1=Vicerrectorado, 2=Educación Continua'),

        ),

        migrations.AlterField(

            model_name='categoriacurso',

            name='nombre',

            field=models.CharField(help_text='Nombre de la categorÃ\xada (Tercer Nivel, Gastronomía, etc.)', max_length=100),

        ),

        migrations.AlterField(

            model_name='curso',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='categoria_curso',

            field=models.ForeignKey(blank=True, help_text='Categoría según la coordinación elegida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='content.categoriacurso'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='clases',

            field=models.CharField(blank=True, help_text='Días de clases', max_length=255, null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='coordinacion',

            field=models.IntegerField(blank=True, choices=[(1, 'Vicerrectorado'), (2, 'Educación Continua')], help_text='1=Vicerrectorado, 2=Educación Continua', null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='costo_matricula',

            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de matrÃ\xadcula inicial en USD', max_digits=10, null=True, verbose_name='Costo de Matrícula'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='cuotas',

            field=models.IntegerField(blank=True, help_text='Cantidad de cuotas en las que se puede diferir el pago', null=True, verbose_name='Número de Cuotas'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='destacado',

            field=models.BooleanField(default=False, help_text='Indica si el curso debe aparecer en la sección de destacados'),

        ),

        migrations.AlterField(

            model_name='curso',

            name='duracion_valor',

            field=models.IntegerField(blank=True, help_text='Cantidad numérica de la duración', null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='fecha_fin',

            field=models.DateField(blank=True, help_text='Fecha de finalización del curso', null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del curso', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='curso',

            name='modalidad',

            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'Híbrida'), ('dual', 'Dual')], help_text='Modalidad del curso', max_length=20, null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='nivel',

            field=models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], help_text='Nivel de dificultad del curso', max_length=50, null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='presentacion',

            field=models.TextField(blank=True, help_text='Presentación/introducción del curso', null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='resolucion',

            field=models.TextField(blank=True, help_text='Número de resolución oficial del curso', null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='tipo',

            field=models.CharField(choices=[('carrera', 'Carrera (Tercer Nivel)'), ('moodle', 'Curso Moodle Destacado')], default='carrera', help_text='Define si es una Carrera de la institución o un curso destacado de Moodle', max_length=20),

        ),

        migrations.AlterField(

            model_name='curso',

            name='titulo_obtenido',

            field=models.CharField(blank=True, help_text='Título que obtiene el estudiante', max_length=255, null=True),

        ),

        migrations.AlterField(

            model_name='curso',

            name='unidad_duracion',

            field=models.CharField(choices=[('horas', 'Horas'), ('anios', 'Años')], default='horas', help_text='Define si la duración es en horas o años', max_length=10),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='archivo_tamano_bytes',

            field=models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='categoria',

            field=models.CharField(choices=[('normativa institucional', 'Normativa Institucional'), ('información económica', 'Infromación Económica'), ('rendición de cuentas', 'Rendición de Cuentas'), ('planificación institucional', 'Planificación Institucional')], help_text='Categoría principal del documento', max_length=100),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='descripcion',

            field=models.TextField(blank=True, help_text='Descripción del contenido del documento', null=True),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='fecha_documento',

            field=models.DateField(help_text='Fecha del documento (fecha de emisión)'),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del documento', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='subcategoria',

            field=models.CharField(choices=[('presupuesto', 'Presupuesto'), ('reglamentos', 'Reglamentos'), ('actas', 'Actas'), ('informes', 'Informes'), ('convenios', 'Convenios'), ('resoluciones', 'Resoluciones'), ('normativa', 'Normativa'), ('financiero', 'Financiero'), ('estatutos', 'Estatutos'), ('politicas', 'Políticas'), ('protocolos', 'Protocolos'), ('manuales', 'Manuales'), ('guias', 'Guías'), ('remuneraciones', 'Remuneraciones'), ('estados_financieros', 'Estados Financieros'), ('planificacion_operativa', 'Planificación Operativa'), ('planificacion_estrategica', 'Planificación Estratégica')], help_text='SubcategorÃ\xada del documento', max_length=100),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='subido_por',

            field=models.ForeignKey(blank=True, help_text='Usuario que subió el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),

        ),

        migrations.AlterField(

            model_name='documentotransparencia',

            name='titulo',

            field=models.CharField(help_text='Título del documento', max_length=255),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='activo',

            field=models.BooleanField(default=True, help_text='Si la etiqueta está activa y disponible para usar'),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='descripcion',

            field=models.TextField(blank=True, help_text='Descripción opcional de la etiqueta', null=True),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la etiqueta', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='etiqueta',

            name='nombre',

            field=models.CharField(help_text='Nombre de la etiqueta (ej: Tecnología, Educación)', max_length=50, unique=True),

        ),

        migrations.AlterField(

            model_name='imagencarrusel',

            name='activo',

            field=models.BooleanField(default=True, help_text='Indica si la imagen está visible'),

        ),

        migrations.AlterField(

            model_name='imagencarrusel',

            name='orden',

            field=models.IntegerField(default=0, help_text='Orden en el que aparecerá en el carrusel (0 es el primero)'),

        ),

        migrations.AlterField(

            model_name='imagencarrusel',

            name='seccion',

            field=models.CharField(choices=[('mesa_tecnica', 'Mesa Técnica'), ('ruta_aprendizaje', 'Ruta de Aprendizaje'), ('historia', 'Nuestra Historia'), ('inicio', 'Inicio Principal')], help_text='Sección donde aparecerá esta imagen en el frontend', max_length=50),

        ),

        migrations.AlterField(

            model_name='imagencarrusel',

            name='titulo',

            field=models.CharField(blank=True, help_text='Título o nombre descriptivo de la imagen (Opcional)', max_length=150, null=True),

        ),

        migrations.AlterField(

            model_name='imagencarrusel',

            name='url_destino',

            field=models.URLField(blank=True, help_text='URL a la que redirigirá al hacer clic (Especial para Mesa Técnica)', max_length=500, null=True),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='acepta_terminos',

            field=models.BooleanField(default=False, help_text='Aceptación de términos y condiciones (requerido)'),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='curso_interes',

            field=models.ForeignKey(help_text='Programa/Curso de interés', on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='content.curso'),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='email',

            field=models.EmailField(help_text='Correo electrónico de contacto', max_length=254),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='fecha_registro',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro de interés'),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del interesado', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='interesado',

            name='telefono',

            field=models.CharField(help_text='Número de teléfono', max_length=15),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='enlace_texto',

            field=models.CharField(blank=True, help_text="Texto del botón del enlace (ej: 'Leer más', 'Inscribirte')", max_length=100, null=True),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='estado',

            field=models.BooleanField(default=False, help_text='Si la noticia está activa (True) o inactiva (False)'),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la noticia popup', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='noticiaspopup',

            name='nombre',

            field=models.CharField(help_text='Título de la noticia emergente', max_length=255),

        ),

        migrations.AlterField(

            model_name='post',

            name='actualizado_en',

            field=models.DateTimeField(auto_now=True, help_text='Fecha de última actualización'),

        ),

        migrations.AlterField(

            model_name='post',

            name='archivo_pdf',

            field=models.FileField(blank=True, help_text='Archivo PDF asociado al post (opcional, útil para Revistas o Blogs)', null=True, upload_to='posts_pdfs/%Y/%m/'),

        ),

        migrations.AlterField(

            model_name='post',

            name='clasificacion',

            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('academico', 'Académico'), ('eventos', 'Eventos'), ('deportes', 'Deportes'), ('comunicados', 'Comunicados')], help_text='Clasificación de la noticia', max_length=50, null=True),

        ),

        migrations.AlterField(

            model_name='post',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),

        ),

        migrations.AlterField(

            model_name='post',

            name='estado',

            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', help_text='Estado de publicación', max_length=20),

        ),

        migrations.AlterField(

            model_name='post',

            name='fecha_publicacion',

            field=models.DateTimeField(blank=True, help_text='Fecha de publicación (visible para usuarios)', null=True),

        ),

        migrations.AlterField(

            model_name='post',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del post', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='post',

            name='meta_descripcion',

            field=models.CharField(blank=True, help_text='Meta descripción para SEO', max_length=160, null=True),

        ),

        migrations.AlterField(

            model_name='post',

            name='slug',

            field=models.SlugField(help_text='URL amigable (se genera automáticamente del tÃ\xadtulo)', max_length=255, unique=True),

        ),

        migrations.AlterField(

            model_name='post',

            name='tipo',

            field=models.CharField(choices=[('noticia', 'Noticia'), ('blog', 'Blog'), ('publicacion', 'Publicación Científica'), ('hitos_logros', 'Hitos y Logros')], help_text='Tipo de contenido', max_length=50),

        ),

        migrations.AlterField(

            model_name='post',

            name='titulo',

            field=models.CharField(help_text='Título del post', max_length=255),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='activo',

            field=models.BooleanField(default=True, help_text='Si el recurso está disponible'),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='creado_en',

            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='duracion_segundos',

            field=models.IntegerField(blank=True, help_text='Duración en segundos (solo para videos)', null=True),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='id',

            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del recurso académico', primary_key=True, serialize=False),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='orden',

            field=models.IntegerField(default=0, help_text='Orden de presentación dentro del curso'),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='plataforma',

            field=models.ForeignKey(help_text='Plataforma donde está alojado el recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='integration.plataforma'),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='tamano_bytes',

            field=models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='tipo',

            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('evaluacion', 'Evaluación'), ('enlace', 'Enlace'), ('documento', 'Documento'), ('presentacion', 'Presentación')], help_text='Tipo de recurso', max_length=50),

        ),

        migrations.AlterField(

            model_name='recursoacademico',

            name='titulo',

            field=models.CharField(help_text='Título del recurso', max_length=255),

        ),

    ]

