# Generated by Django 6.0 on 2026-04-28 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('content', '0018_carrera_cursomoodle_alter_curso_options_and_more'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotonSoporte',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del botón', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del botón (ej: Soporte Moodle, Soporte General)', max_length=100)),
                ('enlace_url', models.URLField(help_text='URL de destino del botón (ej: enlace de WhatsApp)', max_length=500)),
                ('plataforma', models.CharField(blank=True, help_text='A qué plataforma pertenece (ej: moodle, sgac)', max_length=50, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase de icono o nombre de icono (opcional)', max_length=100, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Si el botón está visible en el frontend')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
            ],
            options={
                'verbose_name': 'Botón de Soporte',
                'verbose_name_plural': 'Botones de Soporte',
                'db_table': 'botones_soporte',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriacurso',
            options={'verbose_name': 'CategorÃ\xada de Curso', 'verbose_name_plural': 'CategorÃ\xadas de Cursos'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-creado_en'], 'verbose_name': 'Programa AcadÃ©mico (Base)', 'verbose_name_plural': 'Programas AcadÃ©micos (Base)'},
        ),
        migrations.AlterModelOptions(
            name='imagencarrusel',
            options={'ordering': ['seccion', 'orden', '-creado_en'], 'verbose_name': 'Imagen de Carrusel', 'verbose_name_plural': 'ImÃ¡genes de Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='recursoacademico',
            options={'ordering': ['curso', 'orden'], 'verbose_name': 'Recurso AcadÃ©mico', 'verbose_name_plural': 'Recursos AcadÃ©micos'},
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del acceso', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='plataforma',
            field=models.ForeignKey(blank=True, help_text='Plataforma donde se accediÃ³ al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='integration.plataforma'),
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='sesion',
            field=models.ForeignKey(blank=True, help_text='SesiÃ³n en la que se accediÃ³ al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='auth_app.sesion'),
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='tiempo_acceso_segundos',
            field=models.IntegerField(default=0, help_text='Tiempo que el usuario pasÃ³ con el recurso (en segundos)'),
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='tipo_acceso',
            field=models.CharField(choices=[('descarga', 'Descarga'), ('visualizacion', 'VisualizaciÃ³n'), ('reproduccion', 'ReproducciÃ³n')], help_text='Tipo de acceso realizado', max_length=50),
        ),
        migrations.AlterField(
            model_name='accesorecurso',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que accediÃ³ al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si la autoridad estÃ¡ actualmente en el cargo'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='biografia',
            field=models.TextField(blank=True, help_text='BiografÃ\xada profesional y trayectoria', null=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='cargo',
            field=models.CharField(choices=[('rector', 'Rector'), ('vicerrector', 'Vicerrector'), ('coordinador_academico', 'Coordinador AcadÃ©mico'), ('secretario_general', 'Secretario General'), ('director_carrera', 'Director de Carrera'), ('coordinador_investigacion', 'Coordinador de InvestigaciÃ³n'), ('representante_docente', 'Representante Docentes'), ('representante_estudiante', 'Representante Estudiantes'), ('consejo_regentes', 'Consejo de Regentes')], help_text='Cargo que desempeÃ±a', max_length=100),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n del registro'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin del cargo (NULL si estÃ¡ activo)', null=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='fotografia',
            field=models.ImageField(blank=True, help_text='FotografÃ\xada oficial de la autoridad', null=True, upload_to='autoridades/'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico de la autoridad', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de visualizaciÃ³n en la web (menor = primero)'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='titulo_autoridad',
            field=models.CharField(blank=True, help_text='TÃ\xadtulo acadÃ©mico o profesional (ej: PhD., Msc., Ing., Dr.)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='categoriacurso',
            name='coordinacion',
            field=models.IntegerField(choices=[(1, 'Vicerrectorado'), (2, 'EducaciÃ³n Continua')], help_text='1=Vicerrectorado, 2=EducaciÃ³n Continua'),
        ),
        migrations.AlterField(
            model_name='categoriacurso',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categorÃ\xada (Tercer Nivel, GastronomÃ\xada, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='categoria_curso',
            field=models.ForeignKey(blank=True, help_text='CategorÃ\xada segÃºn la coordinaciÃ³n elegida', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='content.categoriacurso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='clases',
            field=models.CharField(blank=True, help_text='DÃ\xadas de clases', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='coordinacion',
            field=models.IntegerField(blank=True, choices=[(1, 'Vicerrectorado'), (2, 'EducaciÃ³n Continua')], help_text='1=Vicerrectorado, 2=EducaciÃ³n Continua', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de matrÃ\xadcula inicial en USD', max_digits=10, null=True, verbose_name='Costo de MatrÃ\xadcula'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n del registro'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='cuotas',
            field=models.IntegerField(blank=True, help_text='Cantidad de cuotas en las que se puede diferir el pago', null=True, verbose_name='NÃºmero de Cuotas'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Indica si el curso debe aparecer en la secciÃ³n de destacados'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='duracion_valor',
            field=models.IntegerField(blank=True, help_text='Cantidad numÃ©rica de la duraciÃ³n', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de finalizaciÃ³n del curso', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del curso', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('hibrida', 'HÃ\xadbrida'), ('dual', 'Dual')], help_text='Modalidad del curso', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nivel',
            field=models.CharField(blank=True, choices=[('basico', 'BÃ¡sico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], help_text='Nivel de dificultad del curso', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='presentacion',
            field=models.TextField(blank=True, help_text='PresentaciÃ³n/introducciÃ³n del curso', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='resolucion',
            field=models.TextField(blank=True, help_text='NÃºmero de resoluciÃ³n oficial del curso', null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('carrera', 'Carrera (Tercer Nivel)'), ('moodle', 'Curso Moodle Destacado')], default='carrera', help_text='Define si es una Carrera de la instituciÃ³n o un curso destacado de Moodle', max_length=20),
        ),
        migrations.AlterField(
            model_name='curso',
            name='titulo_obtenido',
            field=models.CharField(blank=True, help_text='TÃ\xadtulo que obtiene el estudiante', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='unidad_duracion',
            field=models.CharField(choices=[('horas', 'Horas'), ('anios', 'AÃ±os')], default='horas', help_text='Define si la duraciÃ³n es en horas o aÃ±os', max_length=10),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='archivo_tamano_bytes',
            field=models.BigIntegerField(blank=True, help_text='TamaÃ±o del archivo en bytes', null=True),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='categoria',
            field=models.CharField(choices=[('normativa institucional', 'Normativa Institucional'), ('informaciÃ³n econÃ³mica', 'InfromaciÃ³n EconÃ³mica'), ('rendiciÃ³n de cuentas', 'RendiciÃ³n de Cuentas'), ('planificaciÃ³n institucional', 'PlanificaciÃ³n Institucional')], help_text='CategorÃ\xada principal del documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n del contenido del documento', null=True),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='fecha_documento',
            field=models.DateField(help_text='Fecha del documento (fecha de emisiÃ³n)'),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del documento', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='subcategoria',
            field=models.CharField(choices=[('presupuesto', 'Presupuesto'), ('reglamentos', 'Reglamentos'), ('actas', 'Actas'), ('informes', 'Informes'), ('convenios', 'Convenios'), ('resoluciones', 'Resoluciones'), ('normativa', 'Normativa'), ('financiero', 'Financiero'), ('estatutos', 'Estatutos'), ('politicas', 'PolÃ\xadticas'), ('protocolos', 'Protocolos'), ('manuales', 'Manuales'), ('guias', 'GuÃ\xadas'), ('remuneraciones', 'Remuneraciones'), ('estados_financieros', 'Estados Financieros'), ('planificacion_operativa', 'PlanificaciÃ³n Operativa'), ('planificacion_estrategica', 'PlanificaciÃ³n EstratÃ©gica')], help_text='SubcategorÃ\xada del documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='subido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que subiÃ³ el documento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='titulo',
            field=models.CharField(help_text='TÃ\xadtulo del documento', max_length=255),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si la etiqueta estÃ¡ activa y disponible para usar'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='descripcion',
            field=models.TextField(blank=True, help_text='DescripciÃ³n opcional de la etiqueta', null=True),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico de la etiqueta', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(help_text='Nombre de la etiqueta (ej: TecnologÃ\xada, EducaciÃ³n)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la imagen estÃ¡ visible'),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden en el que aparecerÃ¡ en el carrusel (0 es el primero)'),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='seccion',
            field=models.CharField(choices=[('mesa_tecnica', 'Mesa TÃ©cnica'), ('ruta_aprendizaje', 'Ruta de Aprendizaje'), ('historia', 'Nuestra Historia'), ('inicio', 'Inicio Principal')], help_text='SecciÃ³n donde aparecerÃ¡ esta imagen en el frontend', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='titulo',
            field=models.CharField(blank=True, help_text='TÃ\xadtulo o nombre descriptivo de la imagen (Opcional)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='imagencarrusel',
            name='url_destino',
            field=models.URLField(blank=True, help_text='URL a la que redirigirÃ¡ al hacer clic (Especial para Mesa TÃ©cnica)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='acepta_terminos',
            field=models.BooleanField(default=False, help_text='AceptaciÃ³n de tÃ©rminos y condiciones (requerido)'),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='curso_interes',
            field=models.ForeignKey(help_text='Programa/Curso de interÃ©s', on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='content.curso'),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='email',
            field=models.EmailField(help_text='Correo electrÃ³nico de contacto', max_length=254),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del registro de interÃ©s'),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del interesado', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='telefono',
            field=models.CharField(help_text='NÃºmero de telÃ©fono', max_length=15),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n del registro'),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='enlace_texto',
            field=models.CharField(blank=True, help_text="Texto del botÃ³n del enlace (ej: 'Leer mÃ¡s', 'Inscribirte')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='estado',
            field=models.BooleanField(default=False, help_text='Si la noticia estÃ¡ activa (True) o inactiva (False)'),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico de la noticia popup', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noticiaspopup',
            name='nombre',
            field=models.CharField(help_text='TÃ\xadtulo de la noticia emergente', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, help_text='Fecha de Ãºltima actualizaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='post',
            name='archivo_pdf',
            field=models.FileField(blank=True, help_text='Archivo PDF asociado al post (opcional, Ãºtil para Revistas o Blogs)', null=True, upload_to='posts_pdfs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('institucional', 'Institucional'), ('academico', 'AcadÃ©mico'), ('eventos', 'Eventos'), ('deportes', 'Deportes'), ('comunicados', 'Comunicados')], help_text='ClasificaciÃ³n de la noticia', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n'),
        ),
        migrations.AlterField(
            model_name='post',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], default='borrador', help_text='Estado de publicaciÃ³n', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateTimeField(blank=True, help_text='Fecha de publicaciÃ³n (visible para usuarios)', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del post', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_descripcion',
            field=models.CharField(blank=True, help_text='Meta descripciÃ³n para SEO', max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='URL amigable (se genera automÃ¡ticamente del tÃ\xadtulo)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'Noticia'), ('blog', 'Blog'), ('publicacion', 'PublicaciÃ³n CientÃ\xadfica'), ('hitos_logros', 'Hitos y Logros')], help_text='Tipo de contenido', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='TÃ\xadtulo del post', max_length=255),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='activo',
            field=models.BooleanField(default=True, help_text='Si el recurso estÃ¡ disponible'),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creaciÃ³n del registro'),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='duracion_segundos',
            field=models.IntegerField(blank=True, help_text='DuraciÃ³n en segundos (solo para videos)', null=True),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador Ãºnico del recurso acadÃ©mico', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de presentaciÃ³n dentro del curso'),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='plataforma',
            field=models.ForeignKey(help_text='Plataforma donde estÃ¡ alojado el recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='integration.plataforma'),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='tamano_bytes',
            field=models.BigIntegerField(blank=True, help_text='TamaÃ±o del archivo en bytes', null=True),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='tipo',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('evaluacion', 'EvaluaciÃ³n'), ('enlace', 'Enlace'), ('documento', 'Documento'), ('presentacion', 'PresentaciÃ³n')], help_text='Tipo de recurso', max_length=50),
        ),
        migrations.AlterField(
            model_name='recursoacademico',
            name='titulo',
            field=models.CharField(help_text='TÃ\xadtulo del recurso', max_length=255),
        ),
    ]
