# Generated by Django 6.0 on 2026-05-04 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_botonsoporte_alter_categoriacurso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacurso',
            name='nombre',
            field=models.CharField(help_text='Nombre de la categoría (Tercer Nivel, Gastronomía, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo_matricula',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Costo de matrícula inicial en USD', max_digits=10, null=True, verbose_name='Costo de Matrícula'),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='subcategoria',
            field=models.CharField(choices=[('presupuesto', 'Presupuesto'), ('reglamentos', 'Reglamentos'), ('actas', 'Actas'), ('informes', 'Informes'), ('convenios', 'Convenios'), ('resoluciones', 'Resoluciones'), ('normativa', 'Normativa'), ('financiero', 'Financiero'), ('estatutos', 'Estatutos'), ('politicas', 'Políticas'), ('protocolos', 'Protocolos'), ('manuales', 'Manuales'), ('guias', 'Guías'), ('remuneraciones', 'Remuneraciones'), ('estados_financieros', 'Estados Financieros'), ('planificacion_operativa', 'Planificación Operativa'), ('planificacion_estrategica', 'Planificación Estratégica')], help_text='Subcategoría del documento', max_length=100),
        ),
        migrations.AlterField(
            model_name='interesado',
            name='curso_interes',
            field=models.ForeignKey(blank=True, help_text='Programa/Curso de interés', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='content.curso'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='URL amigable (se genera automáticamente del título)', max_length=255, unique=True),
        ),
    ]
