# Generated by Django 6.0 on 2026-01-14 15:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
        ('integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del curso', primary_key=True, serialize=False)),
                ('codigo_externo', models.CharField(help_text='ID del curso en la plataforma externa (ej:ID en Moodle)', max_length=100)),
                ('titulo', models.CharField(help_text='Titulo del curso', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripcion del curso', null=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoria del curso(Tecnologia,Administracion,etc.)', max_length=100, null=True)),
                ('nivel', models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], help_text='Nivel de dificultad del curso', max_length=50, null=True)),
                ('duracion_horas', models.IntegerField(blank=True, help_text='Duración estimada del curso en horas', null=True)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen/portada del curso', max_length=500, null=True)),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del curso', null=True)),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización del curso', null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='activo', help_text='Estado actual del curso', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('plataforma', models.ForeignKey(help_text='Plataforma a la que pertenece el curso', on_delete=django.db.models.deletion.CASCADE, to='integration.plataforma')),
                ('profesor_responsable', models.ForeignKey(blank=True, help_text='Profesor responsable del curso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RecursoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del recurso académico', primary_key=True, serialize=False)),
                ('codigo_externo', models.CharField(help_text='ID del recurso en la plataforma externa', max_length=100)),
                ('titulo', models.CharField(help_text='Título del recurso', max_length=255)),
                ('tipo', models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('evaluacion', 'Evaluación'), ('enlace', 'Enlace'), ('documento', 'Documento'), ('presentacion', 'Presentación')], help_text='Tipo de recurso', max_length=50)),
                ('formato', models.CharField(blank=True, choices=[('mp4', 'MP4'), ('pdf', 'PDF'), ('html', 'HTML'), ('url', 'URL'), ('docx', 'DOCX'), ('pptx', 'PPTX'), ('xlsx', 'XLSX')], help_text='Formato del archivo', max_length=20, null=True)),
                ('url', models.URLField(help_text='URL del recurso', max_length=500)),
                ('tamano_bytes', models.BigIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('duracion_segundos', models.IntegerField(blank=True, help_text='Duración en segundos (solo para videos)', null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de presentación dentro del curso')),
                ('activo', models.BooleanField(default=True, help_text='Si el recurso está disponible')),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro')),
                ('curso', models.ForeignKey(help_text='Curso al que pertenece este recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='content.curso')),
                ('plataforma', models.ForeignKey(help_text='Plataforma donde está alojado el recurso', on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='integration.plataforma')),
            ],
            options={
                'verbose_name': 'Recurso Académico',
                'verbose_name_plural': 'Recursos Académicos',
                'db_table': 'recursos_academicos',
                'ordering': ['curso', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='AccesoRecurso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del acceso', primary_key=True, serialize=False)),
                ('tipo_acceso', models.CharField(choices=[('descarga', 'Descarga'), ('visualizacion', 'Visualización'), ('reproduccion', 'Reproducción')], help_text='Tipo de acceso realizado', max_length=50)),
                ('porcentaje_completado', models.IntegerField(default=0, help_text='Porcentaje completado del recurso (0-100)')),
                ('tiempo_acceso_segundos', models.IntegerField(default=0, help_text='Tiempo que el usuario pasó con el recurso (en segundos)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del acceso')),
                ('plataforma', models.ForeignKey(blank=True, help_text='Plataforma donde se accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='integration.plataforma')),
                ('sesion', models.ForeignKey(blank=True, help_text='Sesión en la que se accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to='auth_app.sesion')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que accedió al recurso', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_recursos', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(help_text='Recurso que fue accedido', on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='content.recursoacademico')),
            ],
            options={
                'verbose_name': 'Acceso a Recurso',
                'verbose_name_plural': 'Accesos a Recursos',
                'db_table': 'accesos_recursos',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['plataforma'], name='cursos_platafo_4ffdb9_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['codigo_externo'], name='cursos_codigo__ab2396_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['estado'], name='cursos_estado_730766_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['categoria'], name='cursos_categor_ef0463_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['nivel'], name='cursos_nivel_be2d73_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['profesor_responsable'], name='cursos_profeso_e217b3_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoacademico',
            index=models.Index(fields=['curso'], name='recursos_ac_curso_i_fe0f13_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoacademico',
            index=models.Index(fields=['plataforma'], name='recursos_ac_platafo_5978ca_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoacademico',
            index=models.Index(fields=['tipo'], name='recursos_ac_tipo_ff5a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoacademico',
            index=models.Index(fields=['activo'], name='recursos_ac_activo_9239d1_idx'),
        ),
        migrations.AddIndex(
            model_name='recursoacademico',
            index=models.Index(fields=['orden'], name='recursos_ac_orden_b00603_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['recurso'], name='accesos_rec_recurso_00ea46_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['usuario'], name='accesos_rec_usuario_63e529_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['sesion'], name='accesos_rec_sesion__8dce82_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['plataforma'], name='accesos_rec_platafo_f3fe82_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['tipo_acceso'], name='accesos_rec_tipo_ac_0de9dc_idx'),
        ),
        migrations.AddIndex(
            model_name='accesorecurso',
            index=models.Index(fields=['timestamp'], name='accesos_rec_timesta_adb8d9_idx'),
        ),
    ]
