# Generated by Django 6.0 on 2026-01-22 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoticiasPopup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la noticia popup",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Título de la noticia emergente", max_length=255
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Contenido detallado de la noticia (opcional)",
                        null=True,
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen de la noticia popup",
                        null=True,
                        upload_to="noticias_popup/%Y/%m/",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha desde cuando se muestra la noticia"
                    ),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        help_text="Fecha hasta cuando se muestra la noticia"
                    ),
                ),
                (
                    "estado",
                    models.BooleanField(
                        default=False,
                        help_text="Si la noticia está activa (True) o inactiva (False)",
                    ),
                ),
                (
                    "enlace_url",
                    models.URLField(
                        blank=True,
                        help_text="URL opcional si la noticia lleva un enlace externo",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "enlace_texto",
                    models.CharField(
                        blank=True,
                        help_text="Texto del botón del enlace (ej: 'Leer más', 'Inscribirte')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Noticia Popup",
                "verbose_name_plural": "Noticias Popup",
                "db_table": "noticias_popup",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["estado"], name="noticias_po_estado_c26bf1_idx"
                    ),
                    models.Index(
                        fields=["fecha_inicio", "fecha_fin"],
                        name="noticias_po_fecha_i_6858a0_idx",
                    ),
                    models.Index(
                        fields=["creado_en"], name="noticias_po_creado__8db7e9_idx"
                    ),
                ],
            },
        ),
    ]
