# Generated by Django 6.0 on 2026-01-26 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_interesado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Autoridad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la autoridad",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        help_text="Nombres de la autoridad", max_length=100
                    ),
                ),
                (
                    "apellidos",
                    models.CharField(
                        help_text="Apellidos de la autoridad", max_length=100
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("rector", "Rector"),
                            ("vicerrector", "Vicerrector"),
                            ("coordinador_academico", "Coordinador Académico"),
                            ("secretario_general", "Secretario General"),
                            ("director_carrera", "Director de Carrera"),
                            (
                                "coordinador_investigacion",
                                "Coordinador de Investigación",
                            ),
                        ],
                        help_text="Cargo que desempeña",
                        max_length=100,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico institucional", max_length=254
                    ),
                ),
                (
                    "fotografia",
                    models.ImageField(
                        blank=True,
                        help_text="Fotografía oficial de la autoridad",
                        null=True,
                        upload_to="autoridades/",
                    ),
                ),
                (
                    "biografia",
                    models.TextField(
                        blank=True,
                        help_text="Biografía profesional y trayectoria",
                        null=True,
                    ),
                ),
                (
                    "orden",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de visualización en la web (menor = primero)",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si la autoridad está actualmente en el cargo",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(help_text="Fecha de inicio en el cargo"),
                ),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de fin del cargo (NULL si está activo)",
                        null=True,
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Autoridad",
                "verbose_name_plural": "Autoridades",
                "db_table": "autoridades",
                "ordering": ["orden", "apellidos"],
                "indexes": [
                    models.Index(fields=["cargo"], name="autoridades_cargo_d96005_idx"),
                    models.Index(
                        fields=["activo"], name="autoridades_activo_e64532_idx"
                    ),
                    models.Index(fields=["orden"], name="autoridades_orden_53cd99_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentoTransparencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del documento",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título del documento", max_length=255),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del contenido del documento",
                        null=True,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("presupuesto", "Presupuesto"),
                            ("reglamentos", "Reglamentos"),
                            ("actas", "Actas"),
                            ("informes", "Informes"),
                            ("convenios", "Convenios"),
                            ("resoluciones", "Resoluciones"),
                            ("normativa", "Normativa"),
                        ],
                        help_text="Categoría del documento",
                        max_length=100,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        help_text="Archivo PDF del documento",
                        upload_to="transparencia/%Y/",
                    ),
                ),
                (
                    "archivo_nombre",
                    models.CharField(
                        blank=True,
                        help_text="Nombre original del archivo",
                        max_length=255,
                    ),
                ),
                (
                    "archivo_tamano_bytes",
                    models.BigIntegerField(
                        blank=True, help_text="Tamaño del archivo en bytes", null=True
                    ),
                ),
                (
                    "fecha_documento",
                    models.DateField(
                        help_text="Fecha del documento (fecha de emisión)"
                    ),
                ),
                (
                    "subido_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de carga del documento"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que subió el documento",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_subidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Transparencia",
                "verbose_name_plural": "Documentos de Transparencia",
                "db_table": "documentos_transparencia",
                "ordering": ["-fecha_documento", "-subido_en"],
                "indexes": [
                    models.Index(
                        fields=["categoria"], name="documentos__categor_e430cd_idx"
                    ),
                    models.Index(
                        fields=["fecha_documento"],
                        name="documentos__fecha_d_f8fc04_idx",
                    ),
                    models.Index(
                        fields=["subido_en"], name="documentos__subido__90f83c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único del post",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(help_text="Título del post", max_length=255),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL amigable (se genera automáticamente del título)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "resumen",
                    models.TextField(
                        help_text="Resumen corto para vista previa en tarjetas",
                        max_length=500,
                    ),
                ),
                (
                    "contenido",
                    models.TextField(
                        help_text="Contenido completo del post (puede incluir HTML)"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("noticia", "Noticia"),
                            ("blog", "Blog"),
                            ("publicacion", "Publicación Científica"),
                        ],
                        help_text="Tipo de contenido",
                        max_length=50,
                    ),
                ),
                (
                    "imagen_portada",
                    models.ImageField(
                        blank=True,
                        help_text="Imagen principal del post",
                        null=True,
                        upload_to="posts/%Y/%m/",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("archivado", "Archivado"),
                        ],
                        default="borrador",
                        help_text="Estado de publicación",
                        max_length=20,
                    ),
                ),
                (
                    "destacado",
                    models.BooleanField(
                        default=False,
                        help_text="Si es True, aparece en el banner principal",
                    ),
                ),
                (
                    "fecha_publicacion",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de publicación (visible para usuarios)",
                        null=True,
                    ),
                ),
                (
                    "meta_descripcion",
                    models.CharField(
                        blank=True,
                        help_text="Meta descripción para SEO",
                        max_length=160,
                        null=True,
                    ),
                ),
                (
                    "etiquetas",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de etiquetas/tags en formato JSON",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Autor del post",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts_autor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "db_table": "posts",
                "ordering": ["-fecha_publicacion", "-creado_en"],
                "indexes": [
                    models.Index(fields=["tipo"], name="posts_tipo_330be3_idx"),
                    models.Index(fields=["estado"], name="posts_estado_6e24c1_idx"),
                    models.Index(fields=["slug"], name="posts_slug_6da55a_idx"),
                    models.Index(fields=["destacado"], name="posts_destaca_f08576_idx"),
                    models.Index(
                        fields=["fecha_publicacion"], name="posts_fecha_p_30cb63_idx"
                    ),
                    models.Index(fields=["creado_en"], name="posts_creado__2c8849_idx"),
                ],
            },
        ),
    ]
