# Generated by Django 6.0 on 2026-01-29 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_autoridad_documentotransparencia_post"),
        ("integration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaCurso",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "coordinacion",
                    models.IntegerField(
                        choices=[(1, "Vicerrectorado"), (2, "Educación Continua")],
                        help_text="1=Vicerrectorado, 2=Educación Continua",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la categoría (Tercer Nivel, Gastronomía, etc.)",
                        max_length=100,
                    ),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Categoría de Curso",
                "verbose_name_plural": "Categorías de Cursos",
                "db_table": "categorias_curso",
            },
        ),
        migrations.RemoveIndex(
            model_name="curso",
            name="cursos_categor_ef0463_idx",
        ),
        migrations.AddField(
            model_name="curso",
            name="coordinacion",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Vicerrectorado"), (2, "Educación Continua")],
                help_text="1=Vicerrectorado, 2=Educación Continua",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="categoriacurso",
            unique_together={("coordinacion", "nombre")},
        ),
        migrations.AddField(
            model_name="curso",
            name="categoria_curso",
            field=models.ForeignKey(
                blank=True,
                help_text="Categoría según la coordinación elegida",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cursos",
                to="content.categoriacurso",
            ),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(
                fields=["coordinacion"], name="cursos_coordin_057162_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="curso",
            index=models.Index(
                fields=["categoria_curso"], name="cursos_categor_54aaa1_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="curso",
            name="categoria",
        ),
    ]
