# Generated by Django 6.0 on 2026-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0008_remove_curso_cursos_profeso_e217b3_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interesado",
            name="acepta_terminos",
            field=models.BooleanField(
                default=False,
                help_text="Aceptación de términos y condiciones (requerido)",
            ),
        ),
        migrations.AddIndex(
            model_name="interesado",
            index=models.Index(
                fields=["acepta_terminos"], name="interesados_acepta__8d5721_idx"
            ),
        ),
    ]
