# Generated by Django 6.0 on 2026-02-11 15:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_interesado_acepta_terminos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="etiquetas",
        ),
        migrations.CreateModel(
            name="Etiqueta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identificador único de la etiqueta",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre de la etiqueta (ej: Tecnología, Educación)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción opcional de la etiqueta",
                        null=True,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Si la etiqueta está activa y disponible para usar",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación"
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, help_text="Fecha de última actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
                "db_table": "etiquetas",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(fields=["nombre"], name="etiquetas_nombre_a2907d_idx"),
                    models.Index(fields=["activo"], name="etiquetas_activo_144e8c_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="etiquetas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Etiquetas asociadas al post",
                related_name="posts",
                to="content.etiqueta",
            ),
        ),
    ]
